### ISSUE TITLE
Is this project ongoing?

### ISSUE THREAD

**Issue by hanyuone** [intellij-crystal/intellij-crystal#2]
Hello, I'm an avid user of Crystal and I think adding IntelliJ support to Crystal is an extremely exciting thing, especially for larger projects.

There hasn't been much activity over the past few months - is this project still actively being developed on?

**Comment by kingsleyh** [comment]
Hi

Sorry I’m focusing on a blockchain project in Crystal at the moment: https://SushiChain.io

But I believe people are continuing over here: https://github.com/crystal-lang-tools/intellij-crystal-lang

**Comment by hanyuone** [comment]
@kingsleyh That project is put on read-only, currently - as well as that, it hasn't been active for around the same period of time as this project (3 months since last commit).

**Comment by faustinoaq** [comment]
Hi @Qwerp-Derp https://github.com/crystal-lang-tools/intellij-crystal-lang is just a fork to promote this repo. There is not work in progress for intellij-crystal yet, although, we created https://github.com/crystal-lang-tools/intellij-crystal to track new progress.

I think the current [available plugin](https://plugins.jetbrains.com/plugin/10213-crystal-language-plugin) can be used with https://github.com/gtache/intellij-lsp and Scry. Well, I guess I can do some things :wink:

**Comment by hanyuone** [comment]
@faustinoaq I see. Thanks!

**Comment by faustinoaq** [comment]
![screenshot_20180505_014948](https://user-images.githubusercontent.com/3067335/39660962-7707551a-500f-11e8-91a9-5ad7aac0426b.png)

![screenshot_20180505_020720](https://user-images.githubusercontent.com/3067335/39660963-772d1ade-500f-11e8-9fcd-2bc0a918be57.png)

I just got it working with completion, diagnostics, formatting, and go to definition out-the-box :tada: 

Thank to intellij-crystal + intellij-lsp + scry :sunglasses:

**Comment by vlad-ro** [comment]
A new version of the plugin with support for 2018.2 onwards has been published: https://plugins.jetbrains.com/plugin/11232-crystal-language-support-updated-for-v2018-2-onwards
It is published as a fork as the original plugin got dormant.

**Comment by kingsleyh** [comment]
Awesome - sorry that I have not had time to work on this plugin - l will try to make some time after Xmas to pick it up again

**Comment by vlad-ro** [comment]
No worries @kingsleyh, would you still be able to merge PR https://github.com/crystal-lang-tools/intellij-crystal-lang/pull/5 some time soon to support IDEA 2018.2+?

**Comment by kingsleyh** [comment]
Done

**Comment by dragosv** [comment]
I see that only Java have been used. I believe Kotlin would be a much better choice (See also the Rust plugin https://github.com/intellij-rust/intellij-rust). Would it be ok to use Kotlin or maybe switch to it?
