### ISSUE TITLE
I'll refresh this up a bit

### ISSUE THREAD

**Issue by yuriy-yarosh** [intellij-crystal/intellij-crystal#8]
Well, I'd like to use Crystal with a decent IDE, and it was a coincedence that I've bought an intellij IDEA subscription recently 😄

So, this project is pretty stale as far as I can see.
I'd like to improve few things:
 - port existing parser impl to Antlr, instead of Parsec ( it's a JVM env, not a Haskell one 🥇)
 - use kotlin, because it would require less effort
 - fix deps and fatjars, add some gradle tasks
 - more test cases, probably with [pitest](pitest.org) ftw

Thoughts, proposals, ideas ?

**Comment by Iainmon** [comment]
Great idea! I really wish they would continue to work on this project and make it compatible with the 2018 versions.

**Comment by vlad-ro** [comment]
A new version of the plugin with fix support for 2018.2 onwards has been published: https://plugins.jetbrains.com/plugin/11232-crystal-language-support-updated-for-v2018-2-onwards
It is a fork as the original plugin got dormant.

**Comment by dragosv** [comment]
Kotlin would be a great choice other Java. The fully developed Rust plugin is mainly Kotlin as well https://github.com/intellij-rust/intellij-rust.

**Comment by Indribell** [comment]
> A new version of the plugin with fix support for 2018.2 onwards has been published

Unfortunately, its also extreme unstable, resulting in coding with noticeable lag on projects with more then 100 lines of code. To even micro pauses in the order off several seconds ( on Windows ).

**Comment by kingsleyh** [comment]
When Crystal reaches a stable 1.0 I may start working on the plugin again - but at the moment I don’t have any time

**Comment by yuriy-yarosh** [comment]
Yup, it's WIP, but I'm a bit stuck with other projects right now, so this one is not of highest priority, waiting for some things get more stable from the Crystal side too.
